
Import Libraries

In [4]:

import pandas as pd

Step 1: Data Exploration

In [6]:
'''
1) Load the dataset into a Pandas DataFrame.
2) Show the first 5 records.
3) Count the number of entries in each column.
'''

df = pd.read_csv('../data/apple_products.csv')
df.head()

,Product Name,Product URL,Brand,Sale Price,Mrp,Discount Percentage,Number Of Ratings,Number Of Reviews,Upc,Star Rating,Ram
0,"APPLE iPhone 8 Plus (Gold, 64 GB)",https://www.flipkart.com/apple-iphone-8-plus-g...,Apple,49900,49900,0,3431,356,MOBEXRGV7EHHTGUH,4.6,2 GB
1,"APPLE iPhone 8 Plus (Space Grey, 256 GB)",https://www.flipkart.com/apple-iphone-8-plus-s...,Apple,84900,84900,0,3431,356,MOBEXRGVAC6TJT4F,4.6,2 GB
2,"APPLE iPhone 8 Plus (Silver, 256 GB)",https://www.flipkart.com/apple-iphone-8-plus-s...,Apple,84900,84900,0,3431,356,MOBEXRGVGETABXWZ,4.6,2 GB
3,"APPLE iPhone 8 (Silver, 256 GB)",https://www.flipkart.com/apple-iphone-8-silver...,Apple,77000,77000,0,11202,794,MOBEXRGVMZWUHCBA,4.5,2 GB
4,"APPLE iPhone 8 (Gold, 256 GB)",https://www.flipkart.com/apple-iphone-8-gold-2...,Apple,77000,77000,0,11202,794,MOBEXRGVPK7PFEJZ,4.5,2 GB

Step 2: Price Analysis

In [7]:
'''
1) Find the maximum and minimum MRP.
2) Extract product(s) with maximum MRP (e.g., ₹149900).
3) Extract product(s) with minimum MRP (e.g., ₹39900).
4) Extract all iPhones with MRP ≥ ₹1,00,000.
'''

max_mrp = df['Mrp'].max()
min_mrp = df['Mrp'].min()  
print(f"Maximum MRP: ₹{max_mrp}")
print(f"Minimum MRP: ₹{min_mrp}")

max_mrp_products = df[df["Mrp"] == max_mrp].reset_index(drop=True)
min_mrp_products = df[df["Mrp"] == min_mrp].reset_index(drop=True)
print(f"Product(s) with Maximum MRP:\n{max_mrp_products["Product Name"]}")
print(f"Product(s) with Minimun MRP:\n{min_mrp_products["Product Name"]}")

Maximum MRP: ₹149900
Minimum MRP: ₹39900
Product(s) with Maximum MRP:
0          APPLE iPhone 12 Pro (Silver, 512 GB)
1    APPLE iPhone 12 Pro (Pacific Blue, 512 GB)
Name: Product Name, dtype: object
Product(s) with Minimun MRP:
0    APPLE iPhone SE (White, 64 GB)
1    APPLE iPhone SE (Black, 64 GB)
Name: Product Name, dtype: object

Step 3: String Operations

In [8]:
''' 
1) Convert the first product name to UPPERCASE and lowercase.
2) From the 52nd product name, extract characters from index 6–15, convert to UPPERCASE, and strip() extra spaces.
''' 
print("First Product in Upper Case:", df.loc[0, "Product Name"].upper())
print("First Product in Lower Case:", df.loc[0, "Product Name"].lower())

print("52nd Product, characters from index 6-15 in Upper Case:", df.loc[51, "Product Name"][6:16].upper().strip())

First Product in Upper Case: APPLE IPHONE 8 PLUS (GOLD, 64 GB)
First Product in Lower Case: apple iphone 8 plus (gold, 64 gb)
52nd Product, characters from index 6-15 in Upper Case: IPHONE 11

Step 4: Feature Engineering

In [ ]:
''' 
1) Create a new column Model Name by extracting characters from index 6–15 of the Product Name.
2) Add this column to your dataset.
''' 
df['Model Name'] = df['Product Name'].str[6:16].str.strip()
df.to_csv('../data/apple_products_with_model.csv', index=False)
df.head()

,Product Name,Product URL,Brand,Sale Price,Mrp,Discount Percentage,Number Of Ratings,Number Of Reviews,Upc,Star Rating,Ram,Model Name
0,"APPLE iPhone 8 Plus (Gold, 64 GB)",https://www.flipkart.com/apple-iphone-8-plus-g...,Apple,49900,49900,0,3431,356,MOBEXRGV7EHHTGUH,4.6,2 GB,iPhone 8 P
1,"APPLE iPhone 8 Plus (Space Grey, 256 GB)",https://www.flipkart.com/apple-iphone-8-plus-s...,Apple,84900,84900,0,3431,356,MOBEXRGVAC6TJT4F,4.6,2 GB,iPhone 8 P
2,"APPLE iPhone 8 Plus (Silver, 256 GB)",https://www.flipkart.com/apple-iphone-8-plus-s...,Apple,84900,84900,0,3431,356,MOBEXRGVGETABXWZ,4.6,2 GB,iPhone 8 P
3,"APPLE iPhone 8 (Silver, 256 GB)",https://www.flipkart.com/apple-iphone-8-silver...,Apple,77000,77000,0,11202,794,MOBEXRGVMZWUHCBA,4.5,2 GB,iPhone 8 (
4,"APPLE iPhone 8 (Gold, 256 GB)",https://www.flipkart.com/apple-iphone-8-gold-2...,Apple,77000,77000,0,11202,794,MOBEXRGVPK7PFEJZ,4.5,2 GB,iPhone 8 (

Step 5: Sorting

In [10]:
''' 
1)Sort the dataset by Star Rating in descending order.
''' 
sorted_df = df.sort_values(by='Star Rating', ascending=False).reset_index(drop=True)
sorted_df.head()

,Product Name,Product URL,Brand,Sale Price,Mrp,Discount Percentage,Number Of Ratings,Number Of Reviews,Upc,Star Rating,Ram,Model Name
0,"APPLE iPhone 11 Pro Max (Gold, 64 GB)",https://www.flipkart.com/apple-iphone-11-pro-m...,Apple,117100,117100,0,1078,101,MOBFKCTSAPAYNSGG,4.7,4 GB,iPhone 11
1,"APPLE iPhone 11 Pro Max (Midnight Green, 64 GB)",https://www.flipkart.com/apple-iphone-11-pro-m...,Apple,117100,117100,0,1078,101,MOBFKCTSRYPAQNYT,4.7,4 GB,iPhone 11
2,"APPLE iPhone 11 Pro Max (Space Grey, 64 GB)",https://www.flipkart.com/apple-iphone-11-pro-m...,Apple,117100,117100,0,1078,101,MOBFKCTSKDMKCGQS,4.7,4 GB,iPhone 11
3,"APPLE iPhone 11 Pro Max (Midnight Green, 256 GB)",https://www.flipkart.com/apple-iphone-11-pro-m...,Apple,131900,131900,0,1078,101,MOBFKCTSCAAKGQV7,4.7,4 GB,iPhone 11
4,"APPLE iPhone 11 Pro Max (Gold, 256 GB)",https://www.flipkart.com/apple-iphone-11-pro-m...,Apple,131900,131900,0,1078,101,MOBFKCTS7HCHSPFH,4.7,4 GB,iPhone 11

Step 6: Final Report Generation

In [26]:
''' 
1) Create a CSV report file called:
iphone_analysis_report.csv

The report must contain:
1) A summary table (maximum price, minimum price, count of rows).
2) The list of all products ≥ ₹1,00,000.
3) The dataset with the new Model Name column and sorted by Star Rating (descending).
'''


summary_table = pd.DataFrame({
    'Max Price': [max_mrp],
    'Min Price': [min_mrp],
    'Count of Rows': [len(df)]
})

products_above_1l_df = df[df['Mrp'] >= 100000].reset_index(drop=True)
products_above_1l_df.head()

output_path = '../data/iphone_analysis_report.csv'

with open(output_path, 'w') as f:
    f.write("Summary Table \n")
summary_table.to_csv(output_path, mode='a', index=False)

with open(output_path, 'a') as f:
    f.write("\n Products above 1lac\n")
products_above_1l_df.to_csv(output_path, mode='a')

with open(output_path, 'a') as f:
    f.write("\n Sorted Dataset \n")
sorted_df.to_csv(output_path, mode='a')

In [27]:
with pd.ExcelWriter('../data/iphone_analysis_report.xlsx') as writer:
    summary_table.to_excel(writer, sheet_name='Summary', index=False)
    products_above_1l_df.to_excel(writer, sheet_name='Above_1L')
    sorted_df.to_excel(writer, sheet_name='Sorted')